"""Initial migration

Revision ID: c3c17bd211fe
Revises: 
Create Date: 2024-01-13 13:08:23.402553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3c17bd211fe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")
        batch_op.drop_column("title")

    # ### end Alembic commands ###
